language: perl
perl:
  - "5.8.1"
  - "5.8.5"
  - "5.8.8"
  - "5.8.9"
  - "5.10.0"
  - "5.10.1"
  - "5.12.0"
  - "5.12.5"
  - "5.18.2"
  - "5.20.3"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
addons:
  apt:
    packages:
      - bash
      - dash
      - ksh
      - zsh
      - tcsh
      - csh
      - fish
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - local-lib
after_install:
  - make realclean
script:
  - prove -lv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
